# version: '3.8' # 版本号是可选的
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postgresql/data     # ✅ 绑定宿主机目录，持久化数据
      - ./db/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"                  # 将容器的5432端口映射到宿主机的5433端口
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
